Parameters:
  Env:
    Description: Environment Suffix
    Type: String
    Default: dev
Resources:
  APIGWrole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: 
        Fn::Join:
        - "-"
        - - CSD-APIGW-ROLE
          - Ref: Env      
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CSD-LAMBDA-POLICY
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:GetFunctionConfiguration
                Resource: 
                  - Fn::Join:
                    - ":"
                    -
                      - 'arn:aws:lambda'
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - 'function:csd-*'
        - PolicyName: CSD-S3-POLICY
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                   - s3:PutObject
                   - s3:Get*
                   - s3:List*
                Resource:
                   - 'arn:aws:s3:::csd-*'  
        - PolicyName: CSD-CLOUDWATCH-LOG-POLICY
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:GetLogEvents
                  - logs:PutLogEvents
                  - logs:TagLogGroup
                Resource: 
                  - Fn::Join:
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - 'log-group:/aws/apigateway/csd-*'
Outputs:
  APIGWRole:
    Description: Role Name
    Value:
      Ref: APIGWrole