---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template will create a DAX cluster
Parameters:
  Env:
    Description: Environment Suffix
    Type: String
    Default: dev 
  
Resources:
  DaxCluster:
    Type: AWS::DAX::Cluster
    Properties:      
      ClusterName: MyDAXCluster
      NodeType: dax.t2.small
      ReplicationFactor: 1
      IAMRoleARN: arn:aws:iam::108970575545:role/CSD-DAX-ROLE
      Description: DAX cluster created with CloudFormation
      SecurityGroupIds:
      - Fn::GetAtt: [ DaxSecurityGroup, GroupId ]
      SubnetGroupName:
        Ref: subnetGroupClu     
    DependsOn: DaxSecurityGroup    

  DaxSecurityGroup:
    Type: AWS::EC2::SecurityGroup  
    Properties:
      GroupDescription: Daxsecurity
      VpcId: 
        Fn::ImportValue: "CsdNetwork-VpcId"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '8111'
        IpProtocol: tcp
        ToPort: '8111'
      Tags:
      - Key: Name
        Value: CSD-POC-DAX-SG
      - Key: Owner
        Value: OCS
      - Key: Application
        Value: opsTool-POC 
      - Key: Project 
        Value: CSD       
  subnetGroupClu:
    Type: AWS::DAX::SubnetGroup
    Properties:
      SubnetGroupName: DaxSubnetGroup
      Description: Subnet Group For DAX Cluster
      SubnetIds:
      - Fn::ImportValue: "CsdNetwork-DaxSubnet1Id"
      - Fn::ImportValue: "CsdNetwork-DaxSubnet2Id"
Outputs: 
  CsdDaxClusterName:
    Description: DAX Cluster
    Value:
      Ref: DaxCluster 
    Export:
      Name:
        Fn::Sub: "CsdDax-ClusterName"      
  CsdDaxClusterSecurityGroup:
    Description: Dax Cluster Security Group 
    Value:
      Ref: DaxSecurityGroup
    Export:
      Name:
        Fn::Sub: "CsdDaxCluster-SecurityGroup"

