---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Base Infrastructure'

Parameters:
  Env:
    Description: Environment Suffix
    Type: String
    Default: def
  ProjectName:
    Description: Enter the Project name
    Type: String
  EnvironmentName:
    Description: The Name of Environment
    Type: String
    AllowedValues:
    - Development
    - Staging
    - Production
  CIDR:
    Description: The IP address range that you'll use for your VPC
    Default: 10.160.160.0/18
    Type: String
  ServerlessCidrBlock1:
    Description: The IP address range for Serverless Subnet 1
    Type: String
    Default: 10.160.160.0/23

  ServerlessCidrBlock2:
    Description: The IP address range for Serverless Subnet 2
    Type: String
    Default: 10.160.162.0/23

  ContainerCidrBlock1:
    Description: The IP address range for Container Subnet 1
    Type: String
    Default: 10.160.164.0/23

  ContainerCidrBlock2:
    Description: The IP address range for Container Subnet 2
    Type: String
    Default: 10.160.166.0/23

  WanCidrBlock1:
    Description: The IP address range for PUBLIC Subnet 1
    Type: String
    Default: 10.160.168.0/23

  WanCidrBlock2:
    Description: The IP address range for PUBLIC Subnet 2
    Type: String
    Default: 10.160.170.0/23

  DbCidrBlock1:
    Description: The IP address range for Db Subnet 1
    Type: String
    Default: 10.160.172.0/23

  DbCidrBlock2:
    Description: The IP address range for Db Subnet 2
    Type: String
    Default: 10.160.174.0/23

  DaxCidrBlock1:
    Description: The IP address range for Dax Subnet 1
    Type: String
    Default: 10.160.176.0/23

  DaxCidrBlock2:
    Description: The IP address range for Dax Subnet 1
    Type: String
    Default: 10.160.178.0/23    



Resources:
  CSDNETWORKSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        CIDR: !Ref CIDR
        ServerlessCidrBlock1: !Ref ServerlessCidrBlock1

        ServerlessCidrBlock2: !Ref ServerlessCidrBlock2

        ContainerCidrBlock1: !Ref ContainerCidrBlock1

        ContainerCidrBlock2: !Ref ContainerCidrBlock2

        WanCidrBlock1: !Ref WanCidrBlock1

        WanCidrBlock2: !Ref WanCidrBlock2

        DbCidrBlock1: !Ref DbCidrBlock1

        DbCidrBlock2: !Ref DbCidrBlock2

        Env: !Ref Env
      Tags:
        - Key: "Name"
          Value: "Testing"  
      TemplateURL: https://vispolicytest.s3.amazonaws.com/newnetwork.yaml
      TimeoutInMinutes: '15'
  CSDDAXSTACK:
    Type: AWS::CloudFormation::Stack
    DependsOn: CSDNETWORKSTACK
    Properties:
      Parameters:
        Env: !Ref Env
      Tags:
        - Key: "Name"
          Value: "Testing"
      TemplateURL: https://vispolicytest.s3.amazonaws.com/newdax.yaml
      TimeoutInMinutes: '10' 