---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Base Infrastructure'

Parameters:
  DefReadCap:
    Description: Read Capacity Units
    Type: String
    Default: '3'
  DefWriteCap:
    Description: Write Capacity Units
    Type: String
    Default: '3'  
  Env:
    Description: Environment Suffix
    Type: String
    Default: def
  ProjectName:
    Description: Enter the Project name
    Type: String
  EnvironmentName:
    Description: The Name of Environment
    Type: String
    AllowedValues:
    - Development
    - Staging
    - Production
  CIDR:
    Description: The IP address range that you'll use for your VPC
    Default: 10.160.160.0/20
    Type: String
  ServerlessCidrBlock1:
    Description: The IP address range for Serverless Subnet 1
    Type: String
    Default: 10.160.160.0/23

  ServerlessCidrBlock2:
    Description: The IP address range for Serverless Subnet 2
    Type: String
    Default: 10.160.162.0/23

  ContainerCidrBlock1:
    Description: The IP address range for Container Subnet 1
    Type: String
    Default: 10.160.164.0/23

  ContainerCidrBlock2:
    Description: The IP address range for Container Subnet 2
    Type: String
    Default: 10.160.166.0/23

  WanCidrBlock1:
    Description: The IP address range for PUBLIC Subnet 1
    Type: String
    Default: 10.160.168.0/23

  WanCidrBlock2:
    Description: The IP address range for PUBLIC Subnet 2
    Type: String
    Default: 10.160.170.0/23

  DbCidrBlock1:
    Description: The IP address range for Db Subnet 1
    Type: String
    Default: 10.160.172.0/23

  DbCidrBlock2:
    Description: The IP address range for Db Subnet 2
    Type: String
    Default: 10.160.174.0/23

  Subnet1:
    Description: Subnet1 for DAX
    Type: String 
  Subnet2:
    Description: Subnet2 for DAX
    Type: String
  daxsg:
    Description: SG for dax
    Type: String    

 
Resources:
  CSDNETWORKSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        CIDR: !Ref CIDR
        ServerlessCidrBlock1: !Ref ServerlessCidrBlock1
        ServerlessCidrBlock2: !Ref ServerlessCidrBlock2
        ContainerCidrBlock1: !Ref ContainerCidrBlock1
        ContainerCidrBlock2: !Ref ContainerCidrBlock2
        WanCidrBlock1: !Ref WanCidrBlock1
        WanCidrBlock2: !Ref WanCidrBlock2
        DbCidrBlock1: !Ref DbCidrBlock1
        DbCidrBlock2: !Ref DbCidrBlock2
        Env: !Ref Env
      Tags:
        - Key: "Name"
          Value: "Testing"  
      TemplateURL: https://vispolicytest.s3.amazonaws.com/newnetwork.yaml
      TimeoutInMinutes: '15'
  CSDDAXSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        Subnet1: !Ref Subnet1
        Subnet2: !Ref Subnet2
        daxsg: !Ref daxsg
      Tags:
        - Key: "Name"
          Value: "Testing"
      TemplateURL: https://vispolicytest.s3.amazonaws.com/dax.yaml
      TimeoutInMinutes: '10'
    DependsOn: CSDNETWORKSTACK
  CSDDYNAMODBSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DefReadCap: !Ref DefReadCap
        DefWriteCap: !Ref DefWriteCap
        Env: !Ref Env
        ParamStackName: !Ref AWS::StackName
      Tags:
        - Key: "Name"
          Value: "Testing"        
      TemplateURL: https://vispolicytest.s3.amazonaws.com/wm-esb-customer-comm-lookup-qa.yaml
      TimeoutInMinutes: '5'
  CSDLAMBDAROLESTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ParamStackName: !Ref AWS::StackName
      Tags:
        - Key: "Name"
          Value: "Testing"      
      TemplateURL: https://vispolicytest.s3.amazonaws.com/Lambda-IAM-ROLE-TEST.yml
      TimeoutInMinutes: '5'
  CSDAPIGWROLESTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      Tags:
        - Key: "Name"
          Value: "Testing"      
      TemplateURL: https://vispolicytest.s3.amazonaws.com/apigw-IAM-ROLE.yml
      TimeoutInMinutes: '10'
  CSDAPPSYNCROLESTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      Tags:
        - Key: "Name"
          Value: "Testing"
      TemplateURL: https://vispolicytest.s3.amazonaws.com/appsync-IAM-ROLE.yml
      TimeoutInMinutes: '10'
  CSDAMPLIFYROLESTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      Tags:
        - Key: "Name"
          Value: "Testing"        
      TemplateURL: https://vispolicytest.s3.amazonaws.com/CSD-AMPLIFY-IAM-ROLE.yml
      TimeoutInMinutes: '10'
  CSDECSROLESTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      Tags:
        - Key: "Name"
          Value: "Testing"        
      TemplateURL: https://vispolicytest.s3.amazonaws.com/ecs-IAM-ROLE.yml
      TimeoutInMinutes: '10'
  CSDKINESISFIREHOUSEROLESTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      Tags:
        - Key: "Name"
          Value: "Testing"        
      TemplateURL: https://vispolicytest.s3.amazonaws.com/Kinesis-firehose-IAM-ROLE.yml
      TimeoutInMinutes: '10'            
Outputs:
  CsdDriverTableName:
    Value: !GetAtt 'CSDDYNAMODBSTACK.Outputs.CsdDriverTableName'
    Description: Table Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-CsdDriver"
          - Ref: Env
  EsbCustomerCommLookupTableName:
    Value: !GetAtt 'CSDDYNAMODBSTACK.Outputs.EsbCustomerCommLookupTableName'
    Description: Table Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-EsbCustomerCommLookup"
          - Ref: Env
  CsdVehicleTableName:
    Value: !GetAtt 'CSDDYNAMODBSTACK.Outputs.CsdVehicleTableName'
    Description: Table Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-CsdVehicle"
          - Ref: Env
  CsdSiteTableName:
    Value: !GetAtt 'CSDDYNAMODBSTACK.Outputs.CsdSiteTableName'
    Description: Table Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-CsdSite"
          - Ref: Env
  CsdRouteTableName:
    Value: !GetAtt 'CSDDYNAMODBSTACK.Outputs.CsdRouteTableName'
    Description: Table Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-CsdRoute"
          - Ref: Env
  CsdLobTableName:
    Value: !GetAtt 'CSDDYNAMODBSTACK.Outputs.CsdLobTableName'
    Description: Table Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-CsdLob"
          - Ref: Env
  CsdEmployeeTableName:
    Value: !GetAtt 'CSDDYNAMODBSTACK.Outputs.CsdEmployeeTableName'
    Description: Table Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-CsdEmployee"
          - Ref: Env
  LambdaRoleName:
    Value: !GetAtt 'CSDLAMBDAROLESTACK.Outputs.LambdaRoleName'
    Description: Role Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CSD-${AWS::StackName}-LambdaRole"
          - Ref: Env
  APIGWRole:
    Value: !GetAtt 'CSDAPIGWROLESTACK.Outputs.APIGWRole'
    Description: Role Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-APIGWRole"
          - Ref: Env
  APPSYNCRole:
    Value: !GetAtt 'CSDAPPSYNCROLESTACK.Outputs.APPSYNCRole'
    Description: Role Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-AppSyncRole"
          - Ref: Env
  CSDAMPLIFYRole:
    Value: !GetAtt 'CSDAMPLIFYROLESTACK.Outputs.CSDAMPLIFYRole'
    Description: Role Name
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-CsdAmplifyRole"
          - Ref: Env
  ECSIAMRole:
    Value: !GetAtt 'CSDECSROLESTACK.Outputs.ECSIAMRole'
    Description: Role Name
    Export:
      Name:
       Fn::Join:
        - "-"
        - - !Sub "CSD-${AWS::StackName}-ECSRole"
          - Ref: Env
  KINESISFIREHOUSEIAMRole:
    Value: !GetAtt 'CSDKINESISFIREHOUSEROLESTACK.Outputs.KINESISFIREHOUSEIAMRole'
    Description: Role Name
    Export:
      Name:
       Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-KinesisfirehouseRole"
          - Ref: Env
  VPCId:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.VPCId'
    Description: VPCId of the newly created VPC
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-VPCId"
            - Ref: Env
  SecurityGroup1:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.SecurityGroup1'
    Description: SecurityGroup for Serverless subnet
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-ServerlessServerSecuritygroup"
            - Ref: Env   
  SecurityGroup2:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.SecurityGroup2'
    Description: SecurityGroup for CONTAINER Subnet
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-ContainerServerSecuritygroup"
            - Ref: Env
  SecurityGroup3:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.SecurityGroup3'
    Description: SecurityGroup for PUBLIC subnet
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-WanServerSecurityGroup"
            - Ref: Env                      
  SecurityGroup4:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.SecurityGroup4'
    Description: SecurityGroup for Db subnet
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-DbServerSecurityGroup"
            - Ref: Env 
  SecurityGroup5:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.SecurityGroup5'
    Description: InternalSSHSecurityGroup
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-InternalSSHSecurityGroup"
            - Ref: Env  
  ServerlessSubnet1Id:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.ServerlessSubnet1Id'
    Description: SubnetId of the Serverless subnet1
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-ServerlessSubnet1ID"
            - Ref: Env   
  ServerlessSubnet2Id:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.ServerlessSubnet2Id'
    Description: SubnetId of the Serverless subnet2
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-ServerlessSubnet2ID"
            - Ref: Env    
  ContainerSubnet1Id:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.ContainerSubnet1Id'
    Description: SubnetId of the CONTAINER subnet1
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-CONTAINERSubnet1ID"
            - Ref: Env 
  ContainerSubnet2Id:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.ContainerSubnet2Id'
    Description: SubnetId of the CONTAINER subnet2
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-CONTAINERSubnet2ID"
            - Ref: Env   
  WanSubnet1Id:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.WanSubnet1Id'
    Description: SubnetId of the PUBLIC subnet1
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-WanSubnet1Id"
            - Ref: Env    
  WanSubnet2Id:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.WanSubnet2Id'
    Description: SubnetId of the PUBLIC subnet2
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-WanSubnet2Id"
            - Ref: Env  
  DbSubnet1Id:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.DbSubnet1Id'
    Description: SubnetId of the DB subnet1
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-DbSubnet1Id"
            - Ref: Env  
  DbSubnet2Id:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.DbSubnet2Id'
    Description: SubnetId of the DB subnet2
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-DbSubnet2Id"
            - Ref: Env 
  NATGW1ID:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.NATGW1ID'
    Description: NatGateway id of PUBLIC subnet1
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CSD-${AWS::StackName}-NATGW1ID"
            - Ref: Env 
  NATGW2ID:
    Value: !GetAtt 'CSDNETWORKSTACK.Outputs.NATGW2ID'
    Description: NatGateway id of PUBLIC subnet2
    Export:
      Name:
        Fn::Join:
          - "-"
          - - !Sub "CDA-${AWS::StackName}-NATGW2ID"
            - Ref: Env  
  csddaxclustername:
    Value: !GetAtt 'CSDDAXSTACK.Outputs.csddaxclustername'
    Description: DAX Cluster  
    Export:
      Name:
        Fn::Join:
        - "-"
        - - !Sub "CDA-${AWS::StackName}-csddaxclustername"
          - Ref: Env    
