Parameters:
  Env:
    Description: Environment Suffix
    Type: String
    Default: dev
Resources:
  Kinesisrole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: 
        Fn::Join:
        - "-"
        - - CSD-KINESIS-FIREHOUSE-ROLE
          - Ref: Env
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CSD-LAMBDA-POLICY
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:GetFunctionConfiguration
                Resource: 
                  - Fn::Join:
                    - ":"
                    -
                      - 'arn:aws:lambda'
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - 'function:csd-*'
        - PolicyName: CSD-S3-POLICY
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                  - s3:Delete*
                Resource: 
                   - 'arn:aws:s3:::csd-*'   
        - PolicyName: CSD-CLOUDWATCH-LOG-POLICY
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:GetLogEvents
                  - logs:PutLogEvents
                  - logs:TagLogGroup
                Resource: 
                  Fn::Join:
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - 'log-group:/aws/lambda/csd-*:*'
        - PolicyName: CSD-APPSYNC-POLICY
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - appsync:List*
                  - appsync:Get*
                  - appsync:Update*
                  - appsync:Delete*
                Resource: 
                  Fn::Join:
                    - ':'
                    -
                      - 'arn:aws:appsync'
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - 'apis/csd-*'
Outputs:
  KINESISFIREHOUSEIAMRole:
    Description: Role Name
    Value:
      Ref: Kinesisrole