---
AWSTemplateFormatVersion: '2010-09-09'
Description: ' Lambda roles with Dynamo DB'

Parameters:
  DefReadCap:
    Description: Read Capacity Units
    Type: String
    Default: '3'
  DefWriteCap:
    Description: Write Capacity Units
    Type: String
    Default: '3'
  Env:
    Description: Environment Suffix
    Type: String
    Default: def

Resources:
  DYNAMODBSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DefReadCap: !Ref DefReadCap
        DefWriteCap: !Ref DefWriteCap
        Env: !Ref Env
        ParamStackName: !Ref AWS::StackName
      TemplateURL: https://manoj-cfn.s3.ap-south-1.amazonaws.com/wm-esb-customer-comm-lookup-qa.yaml
      TimeoutInMinutes: '10'
  LAMBDAROLESTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
        ParamStackName: !Ref AWS::StackName
      TemplateURL: https://manoj-cfn.s3.ap-south-1.amazonaws.com/Lambda-IAM-ROLE-TEST.yml
      TimeoutInMinutes: '10'
  APIGWIAMSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      TemplateURL: https://manoj-cfn.s3.ap-south-1.amazonaws.com/apigw-IAM-ROLE.yml
      TimeoutInMinutes: '10'
  APPSYNCIAMSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      TemplateURL: https://manoj-cfn.s3.ap-south-1.amazonaws.com/appsync-IAM-ROLE.yml
      TimeoutInMinutes: '10'
  CSDAMPLIFYIAMSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      TemplateURL: https://manoj-cfn.s3.ap-south-1.amazonaws.com/CSD-AMPLIFY-IAM-ROLE.yml
      TimeoutInMinutes: '10'
  CSD-EC2-IAM-STACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      TemplateURL: https://manoj-cfn.s3.ap-south-1.amazonaws.com/CSD-EC2-IAM-ROLE.yml
      TimeoutInMinutes: '10'
  ECS-IAM-STACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      TemplateURL: https://manoj-cfn.s3.ap-south-1.amazonaws.com/ecs-IAM-ROLE.yml
      TimeoutInMinutes: '10'
  KINESIS-FIREHOUSE-IAM-STACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Env: !Ref Env
      TemplateURL: https://manoj-cfn.s3.ap-south-1.amazonaws.com/Kinesis-firehose-IAM-ROLE.yml
      TimeoutInMinutes: '10'         
  
Outputs:
  CsdDriverTableName: 
    Value: !GetAtt 'DYNAMODBSTACK.Outputs.CsdDriverTableName'
    Description: Table Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "${AWS::StackName}-CsdDriver"
          - Ref: Env
  EsbCustomerCommLookupTableName:
    Value: !GetAtt 'DYNAMODBSTACK.Outputs.EsbCustomerCommLookupTableName'
    Description: Table Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "${AWS::StackName}-EsbCustomerCommLookup"
          - Ref: Env      
  CsdVehicleTableName:
    Value: !GetAtt 'DYNAMODBSTACK.Outputs.CsdVehicleTableName'
    Description: Table Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "${AWS::StackName}-CsdVehicle"
          - Ref: Env      
  CsdSiteTableName:
    Value: !GetAtt 'DYNAMODBSTACK.Outputs.CsdSiteTableName'
    Description: Table Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "${AWS::StackName}-CsdSite"
          - Ref: Env      
  CsdRouteTableName:
    Value: !GetAtt 'DYNAMODBSTACK.Outputs.CsdRouteTableName'
    Description: Table Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "${AWS::StackName}-CsdRoute"
          - Ref: Env      
  CsdLobTableName:
    Value: !GetAtt 'DYNAMODBSTACK.Outputs.CsdLobTableName'
    Description: Table Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "${AWS::StackName}-CsdLob"
          - Ref: Env
  CsdEmployeeTableName:
    Value: !GetAtt 'DYNAMODBSTACK.Outputs.CsdEmployeeTableName'
    Description: Table Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "${AWS::StackName}-CsdEmployee"
          - Ref: Env
  LambdaRoleName:
    Value: !GetAtt 'LAMBDAROLESTACK.Outputs.LambdaRoleName'
    Description: Role Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "${AWS::StackName}-LambdaRole"
          - Ref: Env
  APIGW-Role:
    Value: !GetAtt 'APIGW-IAM-STACK.Outputs.APIGW-Role'
    Description: Role Name
    Export:
      Name:
       Fn::Join:
       - "-"
       - - !Sub "${AWS::StackName}-APIGW-Role"
  APPSYNC-Role:
    Value: !GetAtt 'LAMBDAROLESTACK.Outputs.APPSYNC-Role'
    Description: Role Name
    Export: 
      Name: 
        Fn::Join:
        - "-"
        - - !Sub "${AWS::StackName}-AppSyncRole"
          - Ref: Env
  CSD-AMPLIFY-IAM-Role:
    Value: !GetAtt 'APIGW-IAM-STACK.Outputs.CSD-AMPLIFY-IAM-Role'
    Description: Role Name
    Export:
      Name:
       Fn::Join:
       - "-"
       - - !Sub "${AWS::StackName}-CsdAmplify-Role"
  CSD-EC2-IAM-Role:
    Value: !GetAtt 'APIGW-IAM-STACK.Outputs.CSD-EC2-IAM-Role'
    Description: Role Name
    Export:
      Name:
       Fn::Join:
       - "-"
       - - !Sub "${AWS::StackName}-CsdEc2-Role"
  ECS-IAM-Role:
    Value: !GetAtt 'APIGW-IAM-STACK.Outputs.ECS-IAM-Role'
    Description: Role Name
    Export:
      Name:
       Fn::Join:
       - "-"
       - - !Sub "${AWS::StackName}-ECS-Role"
  KINESIS-FIREHOUSE-IAM-Role:
    Value: !GetAtt 'APIGW-IAM-STACK.Outputs.KINESIS-FIREHOUSE-IAM-Role'
    Description: Role Name
    Export:
      Name:
       Fn::Join:
       - "-"
       - - !Sub "${AWS::StackName}-Kinesisfirehouse-Role"    
    
  
  